apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ryrg4sr8a-nodejs 
  janus-idp.io/tekton: ryrg4sr8a-nodejs
  backstage.io/kubernetes-id: ryrg4sr8a-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ryrg4sr8a-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml